name: CI-Python-Production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: .
        run: |
          pip install .

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install build tools
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install setuptools
          pip install wheel

      - name: Build package
        working-directory: .
        run: python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        working-directory: .
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
